### ISSUE TITLE
microbiome user:  farmm, stratification does not seem to work

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-eda#5]
email on Apr 11 2024
ReplyTo: [hawa.patel@mail.utoronto.ca](mailto:hawa.patel@mail.utoronto.ca)

When attempting to visualize data in the FARMM Study, under the 'browse and subset' tab, when selecting filters, specifically choosing to filter based on Clinical history -> Antibiotic medication related to sample collection -> choosing all three options: antibiotics treatment, post antibiotics, and pre antibiotics. These are the three groups I am interested in comparing. Whenever i go to visualize the data using any method, be it beta diversity, alpha diversity etc., the only graph that shows up after selecting for stratification variable "Antibiotic medication related to sample collection" is the pre-antibiotics data, the other 2 categories (post antibiotics and antibiotics treatment) do not show up at all, and only show up if the pre-antibiotics option is deselected. Why is this?? What can I do. Thank you

**Comment by d-callan** [comment]
im not convinced this is a backend issue. i can see the two missing values are in the response

![image](https://github.com/VEuPathDB/service-eda/assets/53306535/1794a904-e3aa-40f0-88f1-5a71c89d99fb)

**Comment by dmfalke** [comment]
My first thought is that this could be related to filter sensitivity. I will take a closer look later today.

**Comment by dmfalke** [comment]
I stand corrected. The reason this is happening is that the variable's vocabulary only includes the value `Pre antibiotics`. That vocabulary is used by stratification, etc. I think the reason is so that the values are ordered in a specific way (if ordinal, as this variable happens to be).

**Comment by aurreco-uga** [comment]
from dave:
[https://github.com/VEuPathDB/ApiCommonData/blob/572804e4288f692af88d623ed7e4d5e2cd[…]/ontology/Microbiome/studies/farmm_metagenomics/owlOverride.csv](https://github.com/VEuPathDB/ApiCommonData/blob/572804e4288f692af88d623ed7e4d5e2cd68195b/Load/ontology/Microbiome/studies/farmm_metagenomics/owlOverride.csv#L8)
[owlOverride.csv](https://github.com/VEuPathDB/ApiCommonData/blob/572804e4288f692af88d623ed7e4d5e2cd68195b/Load/ontology/Microbiome/studies/farmm_metagenomics/owlOverride.csv)
"EUPATH_0009125","Antibiotic medication related to sample collection","FARMM_metagenomics.txt::antibiotics","FARMM_metagenomics.txt",,,"yes",,,,,,,,,,,,"[""Pre antibiotics""]"
<https://github.com/[VEuPathDB/ApiCommonData](https://github.com/VEuPathDB/ApiCommonData)|VEuPathDB/ApiCommonData>VEuPathDB/ApiCommonData | Added by [GitHub](https://epvb.slack.com/services/B01VDBGRK62)

(https://epvb.slack.com/archives/GBDR4LDNC/p1713193966526009?thread_ts=1713193514.327719&cid=GBDR4LDNC)
this explains the problem, and if this file is the complete list of variable with overridden vocabs, then it would be pretty easy to manually check.

**Comment by jaycolin** [comment]
Study reloaded, vocabulary issue resolved

**Comment by dmfalke** [comment]
does the metadata cache need to be invalidated?

**Comment by dmfalke** [comment]
i see it's fixed on qa. can this easily be fixed on prod? do we want that? @aurreco-uga @dpbisme ?

**Comment by aurreco-uga** [comment]
i think so if not too complicated.

**Comment by aurreco-uga** [comment]
<img width="1232" alt="Screenshot 2024-04-15 at 3 27 41 PM" src="https://github.com/VEuPathDB/service-eda/assets/16354313/30e716df-6ae1-4ad6-8ad7-66bfb8a5880a">
