### ISSUE TITLE
Unable to read compute outputs

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/service-eda#7]
Using dave's mbio dev site, I'm seeing that all the compute apps are having trouble getting the completed compute data. For example:

the request
```
{"studyId":"Bangladesh_healthy_5yr-1","filters":[],"config":{"outputEntityId":"EUPATH_0000813","points":"outliers","mean":"TRUE","xAxisVariable":{"entityId":"EUPATH_0000096","variableId":"ENVO_01000739"},"facetVariable":[],"showMissingness":"FALSE"},"computeConfig":{"collectionVariable":{"entityId":"EUPATH_0000813","collectionId":"EUPATH_0009257"},"alphaDivMethod":"simpson"}}
```

returned the following error

```
2024-04-15 07:10:03.256 [rid:68hA1][jid:][p:] ERROR ErrorMapper:68 - Caught Exception:
 jakarta.ws.rs.ServerErrorException: Unable to make compute request or read/convert response
```

I can see in the RServe logs that the compute succeeded, but i think there's a mismatch between the output and reading into the ... well what was the data service :) . 
I've seen the same error for alpha diversity, beta diversity, ranked abundance, and differential abundance. For the correlation apps, we don't see the same error but we do see the same result - the `bipartitenetwork` request returns a 204, even though the correlation computation succeeds. The correlation backend works a little differently than the other four apps because it doesn't read data into plot.data to do any wrangling, so perhaps this is the cause of the difference. 

Anywho, any insight would be very helpful!

**Comment by dmgaldi** [comment]
This looks like an environment configuration issue: 

```
ESC[mESC[32m2024-04-15 07:19:38.172 [rid:3QSFq][jid:][p:] INFO  ClientUtil:77 - Will send following POST request to http://localhost:8080/computes/alphadiv?autostart=false
```

This line in the environment:
```
      "COMPUTE_SERVICE_URL=http://localhost:8080",
```

Should read:
```
      "COMPUTE_SERVICE_URL=http://localhost:80",
```

**Comment by aurreco-uga** [comment]
fixed by dan april 15 2024
