### ISSUE TITLE
Map/EDA: problem with newlines in data streams?

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/service-eda#73]
Bug observed on dfalke-b.vectorbase.org with the new HTTP-less back end.
No issues with the production site.

Need to apply these filters (sorry)

Species
![image](https://github.com/user-attachments/assets/602ba07b-512c-47c5-8d18-105724fd6197)

Insecticide
![image](https://github.com/user-attachments/assets/d08c5f83-04a9-4f5e-bc4b-73fb1aa885c8)

Continent = Africa

Then double-click on the 2450 marker 
![image](https://github.com/user-attachments/assets/0c658877-7022-45c9-9647-4c9d4d5c3799)

![image](https://github.com/user-attachments/assets/98a04433-84b5-40d9-b746-5d2201c447fd)

```
{
"status":"server-error",
"message":"Expected 8 columns but parsed 7 in line:\nase15189545|IRBFC7807\tIRbase15189545|IRbase15189545_99\tIRbase15189545\tkk\t-17.92\t15.95\tAnopheles arabiensis","requestId":"52QHozk4AidenKRilRhxbX"}
```

**Comment by Foxcapades** [comment]
I have not yet been able to reproduce the issue, I followed the steps above but the end result was the map zooming in on the area around the 2450 marker.


**Filters**
![Snapshot_2024-12-20_12-25-49](https://github.com/user-attachments/assets/ee94e038-0e9c-4919-af0d-fd923e1d5f2f)
![Snapshot_2024-12-20_12-26-35](https://github.com/user-attachments/assets/5767d510-d5ea-4bfc-a6ce-c7f632fa8953)

**Mouse Over Marker**
![Snapshot_2024-12-20_12-26-46](https://github.com/user-attachments/assets/e60abe77-f9c1-4085-9c53-3bb5e11caa31)

**Double Click Marker**
![Snapshot_2024-12-20_12-26-54](https://github.com/user-attachments/assets/de24d56b-79a7-46a9-a2bd-58baadd9b355)

**Comment by Foxcapades** [comment]
Scratch that, was able to reproduce!  I didn't realize that continent was a variable, once applied i got the error.

**Comment by Foxcapades** [comment]
Fixed by adding the line:
https://github.com/VEuPathDB/service-eda/blob/master/src/main/kotlin/org/veupathdb/service/eda/merge/core/MergeDataInputStream.kt#L95

This request had the exact right amount of data to cause an infinite loop on the last 106 bytes of data in the tabular result.  The exception thrown was a result of trying to parse the repeated incomplete line.
